### ISSUE TITLE
where is wasm used?

### ISSUE THREAD

**Issue by AndySchroder** [lightninglabs/lnc-rn#23]
At https://github.com/lightninglabs/lnc-rn/blob/c368cb631f7fa60b7c048969eca7e6714a677d04/README.md?plain=1#L52 you talk about wasm files. Also, if i search this repository for wasm, I get a few results: https://github.com/lightninglabs/lnc-rn/search?q=wasm . However, here you say that React Native doesn't support wasm: https://github.com/ZeusLN/zeus/issues/1068#issuecomment-1368155824 .

**Comment by kaloudis** [comment]
The RN version uses native binaries built from golang using gomobile. Some of the references in the docs to wasm are from the lnc-web repo. We'll update this. Thanks for the heads up.

**Comment by kaloudis** [comment]
https://github.com/lightninglabs/lnc-rn/pull/24
